# Generated by Django 4.1.2 on 2022-10-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_project_start_date_alter_project_stop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
