# Generated by Django 4.1.2 on 2022-10-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_project_start_date_alter_project_stop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_status',
            field=models.BooleanField(default=False),
        ),
    ]
