# Generated by Django 4.1.2 on 2022-10-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_project_created_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
