# Generated by Django 4.1.2 on 2022-10-07 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_rename_department_departmen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departmen',
            new_name='Department',
        ),
    ]
