# Generated by Django 4.1.2 on 2022-10-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_rename_departmen_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                default="default_user_image.png", upload_to="users"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="projects",
            field=models.ManyToManyField(blank=True, to="company.project"),
        ),
    ]
